### ISSUE TITLE
Pip install doesn't automatically install Patsy

### ISSUE THREAD

**Issue by jdavidheiser** [yhat/ggplot#233]
Just tried to pip install (version 0.4.7), and the dependencies seem to not be picked up correctly for pip - specifically, I had to manually install Patsy first.  Looking at the source, it seems that setup.py correctly identifies patsy as a dependency, so this may already be fixed in the development version, but I thought it was worth pointing out.

**Comment by glamp** [comment]
fixed

**Comment by iustitia** [comment]
I believe it is not solved, as this issue happened to me today.
